# Generated by Django 5.0 on 2025-11-04 22:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_teacher_remove_coursemember_course_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='core_catego_name_6ef604_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_sku_a1eae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_name_be3252_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_categor_32e322_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='core_stockt_product_84e493_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='core_stockt_created_d9eb63_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='core_stockt_transac_be70c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='core_suppli_name_c90f73_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nama kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='core.category', verbose_name='kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stok minimum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='nama produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='harga beli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='harga jual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jumlah stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='core.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='catatan'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='core.product', verbose_name='produk'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='jumlah'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3, verbose_name='tipe transaksi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(verbose_name='alamat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nama supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telepon'),
        ),
    ]
